# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v1
    - name: Run make
      run: |
        find . -name "*.dot" | xargs -n1 touch
        find . -name "*.dot" | sed -e "s/\.dot/.svg/g" | xargs make
        git add .
        git config user.name "Isaac Sanders"
        git config user.email "isaac@isaacbfsanders.com"
        git commit -m "Generate Graphviz Files"
        git push origin master
